apiVersion: v1
kind: PersistentVolume
metadata:
  name: qa-mms-app-efs
  namespace: mms-app
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  cis:
    volumeHandle: fs-qaqaqa
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-999aaa999
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  volumeMode: Filesystem
