// Code generated by pluginator on ArmadaCRDRegister; DO NOT EDIT.
package register

import (
	"github.com/keleustes/armada-crd/pkg/apis/armada/v1alpha1"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/kustomize/api/resmap"
)

// plugin loads the ArmadaChart CRD scheme into kustomize
type ArmadaCRDRegisterPlugin struct {
}

//nolint: golint

func (p *ArmadaCRDRegisterPlugin) Config(
	_ *resmap.PluginHelpers, _ []byte) (err error) {

	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	return v1alpha1.SchemeBuilder.AddToScheme(scheme.Scheme)
}

func (p *ArmadaCRDRegisterPlugin) Transform(m resmap.ResMap) error {
	return nil
}

func NewArmadaCRDRegisterPlugin() resmap.TransformerPlugin {
	return &ArmadaCRDRegisterPlugin{}
}
