// Code generated by pluginator on KfDefCRDRegister; DO NOT EDIT.
package register

import (
	"github.com/keleustes/armada-crd/pkg/apis/kubeflow/v1beta1"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/kustomize/api/resmap"
)

// plugin loads the KfDefChart CRD scheme into kustomize
type KfDefCRDRegisterPlugin struct {
}

//nolint: golint

func (p *KfDefCRDRegisterPlugin) Config(
	_ *resmap.PluginHelpers, _ []byte) (err error) {

	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	return v1beta1.SchemeBuilder.AddToScheme(scheme.Scheme)
}

func (p *KfDefCRDRegisterPlugin) Transform(m resmap.ResMap) error {
	return nil
}

func NewKfDefCRDRegisterPlugin() resmap.TransformerPlugin {
	return &KfDefCRDRegisterPlugin{}
}
