// Code generated by pluginator on MonitoringCRDRegister; DO NOT EDIT.
package register

import (
	"github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/kustomize/api/resmap"
)

// plugin loads the argoproj Rollout CRD scheme into kustomize
type MonitoringCRDRegisterPlugin struct {
}

//nolint: golint

func (p *MonitoringCRDRegisterPlugin) Config(
	_ *resmap.PluginHelpers, _ []byte) (err error) {

	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	return v1.SchemeBuilder.AddToScheme(scheme.Scheme)
}

func (p *MonitoringCRDRegisterPlugin) Transform(m resmap.ResMap) error {
	return nil
}

func NewMonitoringCRDRegisterPlugin() resmap.TransformerPlugin {
	return &MonitoringCRDRegisterPlugin{}
}
