// Code generated by pluginator on OpenShiftCRDRegister; DO NOT EDIT.
package register

import (
	"github.com/openshift/api"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/kustomize/api/resmap"
)

// plugin loads the OpenShift CRD scheme into kustomize
type OpenShiftCRDRegisterPlugin struct {
}

//nolint: golint

func (p *OpenShiftCRDRegisterPlugin) Config(
	_ *resmap.PluginHelpers, _ []byte) (err error) {

	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	return api.Install(scheme.Scheme)
}

func (p *OpenShiftCRDRegisterPlugin) Transform(m resmap.ResMap) error {
	return nil
}

func NewOpenShiftCRDRegisterPlugin() resmap.TransformerPlugin {
	return &OpenShiftCRDRegisterPlugin{}
}
