// Code generated by pluginator on RolloutCRDRegister; DO NOT EDIT.
package register

import (
	"github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/kustomize/api/resmap"
)

// plugin loads the argoproj Rollout CRD scheme into kustomize
type RolloutCRDRegisterPlugin struct {
}

//nolint: golint

func (p *RolloutCRDRegisterPlugin) Config(
	_ *resmap.PluginHelpers, _ []byte) (err error) {

	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	return v1alpha1.SchemeBuilder.AddToScheme(scheme.Scheme)
}

func (p *RolloutCRDRegisterPlugin) Transform(m resmap.ResMap) error {
	return nil
}

func NewRolloutCRDRegisterPlugin() resmap.TransformerPlugin {
	return &RolloutCRDRegisterPlugin{}
}
