// Code generated by pluginator on WorkflowCRDRegister; DO NOT EDIT.
package register

import (
	"github.com/argoproj/argo/pkg/apis/workflow/v1alpha1"
	"k8s.io/client-go/kubernetes/scheme"
	"sigs.k8s.io/kustomize/api/resmap"
)

// plugin loads the argoproj Rollout CRD scheme into kustomize
type WorkflowCRDRegisterPlugin struct {
}

//nolint: golint

func (p *WorkflowCRDRegisterPlugin) Config(
	_ *resmap.PluginHelpers, _ []byte) (err error) {

	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	return v1alpha1.SchemeBuilder.AddToScheme(scheme.Scheme)
}

func (p *WorkflowCRDRegisterPlugin) Transform(m resmap.ResMap) error {
	return nil
}

func NewWorkflowCRDRegisterPlugin() resmap.TransformerPlugin {
	return &WorkflowCRDRegisterPlugin{}
}
