apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labeltransformer
labels:
  env: canary
fieldSpecs:
- path: metadata/labels
  create: true
  kind: Service
- path: spec/selector
  create: true
  kind: Service
- path: metadata/labels
  create: true
  kind: Deployment
- path: spec/selector/matchLabels
  create: true
  kind: Deployment
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
