apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: puppetserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: puppetserver
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: main-route
        # namespace: default
      target:
        type: Value
        value: 10k
