// Code generated by "stringer -type=BuiltinPluginType"; DO NOT EDIT.

package builtinhelpers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[AnnotationsTransformer-1]
	_ = x[ConfigMapGenerator-2]
	_ = x[HashTransformer-3]
	_ = x[ImageTagTransformer-4]
	_ = x[InventoryTransformer-5]
	_ = x[KindFilterTransformer-6]
	_ = x[KindOrderTransformer-7]
	_ = x[LabelTransformer-8]
	_ = x[LegacyOrderTransformer-9]
	_ = x[NamespaceTransformer-10]
	_ = x[PatchJson6902Transformer-11]
	_ = x[PatchStrategicMergeTransformer-12]
	_ = x[PatchTransformer-13]
	_ = x[PrefixSuffixTransformer-14]
	_ = x[ReplicaCountTransformer-15]
	_ = x[SecretGenerator-16]
}

const _BuiltinPluginType_name = "UnknownAnnotationsTransformerConfigMapGeneratorHashTransformerImageTagTransformerInventoryTransformerKindFilterTransformerKindOrderTransformerLabelTransformerLegacyOrderTransformerNamespaceTransformerPatchJson6902TransformerPatchStrategicMergeTransformerPatchTransformerPrefixSuffixTransformerReplicaCountTransformerSecretGenerator"

var _BuiltinPluginType_index = [...]uint16{0, 7, 29, 47, 62, 81, 101, 122, 142, 158, 180, 200, 224, 254, 270, 293, 316, 331}

func (i BuiltinPluginType) String() string {
	if i < 0 || i >= BuiltinPluginType(len(_BuiltinPluginType_index)-1) {
		return "BuiltinPluginType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuiltinPluginType_name[_BuiltinPluginType_index[i]:_BuiltinPluginType_index[i+1]]
}
